name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go mod vendor; go build

    - name: Test
      run: go test -coverprofile=coverage.out -v ./... && go tool cover -html=coverage.out -o=coverage.html 

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
